# Generated by Django 5.2.1 on 2025-05-19 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_residentialaspectcategory_options'),
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positivepoints',
            name='residential_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.residentialaspectcategory', verbose_name='Categoria residencial'),
        ),
        migrations.AddField(
            model_name='positivepoints',
            name='urban_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.urbanaspectcategory', verbose_name='Categoria urbana'),
        ),
    ]
