# Generated by Django 5.2.1 on 2025-05-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characteristics', '0003_negativepoints_residential_aspect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('state', models.CharField(choices=[('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('PR', 'Paraná')], verbose_name='Estado')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('is_considered', models.BooleanField(default=False, verbose_name='Considerado?')),
                ('is_coastal', models.BooleanField(default=False, verbose_name='Cidade costeira?')),
                ('employment_outlook', models.IntegerField(blank=True, choices=[(1, 'Muito Baixa'), (2, 'Baixa'), (3, 'Média'), (4, 'Alta'), (5, 'Muito Alta')], null=True, verbose_name='Probabilidade de emprego')),
                ('negative_points', models.ManyToManyField(blank=True, related_name='cities', to='characteristics.negativepoints', verbose_name='Pontos negativos')),
                ('positive_points', models.ManyToManyField(blank=True, related_name='cities', to='characteristics.positivepoints', verbose_name='Pontos positivos')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
    ]
