# Generated by Django 5.2.1 on 2025-05-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_propertytype_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyType',
            new_name='ResidentialAspectCategory',
        ),
        migrations.AlterModelOptions(
            name='residentialaspectcategory',
            options={'verbose_name': 'Categoria residêncial', 'verbose_name_plural': 'Categorias residênciais'},
        ),
    ]
