# Generated by Django 5.2.1 on 2025-05-19 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0005_alter_residentialaspectcategory_options'),
        ('characteristics', '0003_negativepoints_residential_aspect_and_more'),
        ('cities', '0001_initial'),
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtde Quartos')),
                ('is_kitchen_separate', models.BooleanField(blank=True, null=True, verbose_name='Cozinha separada')),
                ('kitchen_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cor da cozinha')),
                ('is_living_room_separate', models.BooleanField(blank=True, null=True, verbose_name='Sala de Estar')),
                ('living_room_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cor da sala de estar')),
                ('is_dinning_room_separate', models.BooleanField(blank=True, null=True, verbose_name='Sala de Jantar')),
                ('dinning_room_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cor da sala de jantar')),
                ('has_yard', models.BooleanField(default=False, verbose_name='Tem quintal?')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Área em m²')),
                ('has_garage', models.BooleanField(default=False, verbose_name='Tem garagem?')),
                ('garage_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtde carros na garagem')),
                ('pets_allowed', models.BooleanField(default=False, verbose_name='Permite animal')),
                ('is_considered', models.BooleanField(default=False, verbose_name='Considerado')),
                ('is_condominium', models.BooleanField(default=False, verbose_name='Condomínio')),
                ('is_available', models.BooleanField(default=False, verbose_name='Disponível')),
                ('for_rent', models.BooleanField(default=False, verbose_name='Aluguel')),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor aluguel')),
                ('for_sale', models.BooleanField(default=False, verbose_name='Venda')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de venda')),
                ('links', models.TextField(blank=True, null=True, verbose_name='Links')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Contato')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='cities.city', verbose_name='Cidade')),
                ('negative_points', models.ManyToManyField(blank=True, related_name='properties_negative', to='characteristics.negativepoints', verbose_name='Pontos negativos')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='neighborhood.neighborhood', verbose_name='Bairro')),
                ('positive_points', models.ManyToManyField(blank=True, related_name='properties_positive', to='characteristics.positivepoints', verbose_name='Pontos positivos')),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties_of_this_type', to='categories.residentialaspectcategory', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
            },
        ),
        migrations.CreateModel(
            name='FinancingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150, verbose_name='Nome do banco')),
                ('method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Método')),
                ('financed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor financiado')),
                ('total_financed_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total a ser pago')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da parcela')),
                ('number_of_installments', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtde de parcelas')),
                ('allows_amortization', models.BooleanField(default=False, verbose_name='Amortiza')),
                ('via_real_estate_agency', models.BooleanField(default=False, verbose_name='Feito por imobiliária')),
                ('agency_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da imobiliária')),
                ('is_direct_with_owner', models.BooleanField(default=False, verbose_name='Direto com dono')),
                ('direct_owner_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do dono')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Informações de contato')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financing_options', to='property.property', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Opção de financiamento',
                'verbose_name_plural': 'Opções de financiamentos',
            },
        ),
    ]
