name: Deploy to Production

# Aciona o workflow em todo push para a branch 'main'
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # Usa a última versão do Ubuntu como ambiente para rodar os comandos
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Clona seu repositório para dentro do ambiente virtual do GitHub
    - name: Checkout code
      uses: actions/checkout@v4

    # Passo 2: Ação que executa comandos SSH no seu servidor
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22 # Porta SSH, geralmente 22
        script: |
          # Navega até a pasta do projeto no servidor
          cd ~/onde-morar

          # Puxa as últimas atualizações do código da branch main
          git pull origin main

          # Ativa o ambiente virtual
          source venv/bin/activate

          # Instala qualquer nova dependência
          pip install -r requirements.txt

          # Roda as migrações do banco de dados (se houver)
          python manage.py migrate --noinput

          # Coleta todos os arquivos estáticos
          python manage.py collectstatic --noinput

          # Reinicia o serviço do Gunicorn para aplicar as alterações do código
          sudo systemctl restart gunicorn.service

          echo "Deploy finalizado com sucesso!"